### ISSUE TITLE
Rigidel

### ISSUE THREAD

**Issue by Awesome3040384034** [staticvariablejames/ChooseYourOwnLump#1]
So I know is probably been years since someone has been on this site but, Rigidel is only active when the number of building ends in zero; and with an odd amount of grandmas every time for me Rigidel is never active. Is there something wrong I am doing or am I stupid and don't even understand how to use this Add on? (If so tell me how to properly use it :D)

**Comment by staticvariablejames** [comment]
Rigidel demands the _total_ amount of buildings to end in zero. So 23 temples plus 37 grandmas (and no other building) satisfy the requirements.

**Comment by Awesome3040384034** [comment]
I AM VERY DUMB WHAT LOL HOW I AM THAT STUPID LOL XD thanks though
