### ISSUE TITLE
Algorithm appears to be off

### ISSUE THREAD

**Issue by smurfhunter** [staticvariablejames/ChooseYourOwnLump#2]
Has the sugar lump algorithm changed? I've set my items up so it predicts golden for every day this week and refreshed dozens of times (was also garden hunting some queen beats) and have yet to manipulate one golden. I'm wondering if an update broke this?

**Comment by staticvariablejames** [comment]
Nothing changed in the past few months, so things should be working fine. Are you loading the save game with Options -> Import Save? What does the tooltip guide says? (Sorry for the delay in answering...)

**Comment by smurfhunter** [comment]
I don't even remember what the cause of this was, but I have 100%ed cookie clicker at this point so I think we can close this issue hahaha
