### ISSUE TITLE
可以为插件提供一个steam版本吗?   Is there a Steam version for the plugin?

### ISSUE THREAD

**Issue by lolisix** [staticvariablejames/ChooseYourOwnLump#3]
可以为插件提供一个steam版本吗?
我最先尝试在workshop文件夹里面建立一个名为ChooseYourOwnLump的子文件夹,随后在这个子文件夹里面仿造其他插件,建立一个main.js与info.txt, 将https://staticvariablejames.github.io/ChooseYourOwnLump/dist/main.js 里面的所有内容放入main,js, 再在info.txt里面写入`{
	"Name": "Choose Your Own Lump!",
	"ID": "Choose Your Own Lump!",
	"Author": "staticvariablejames",
	"Description": "This is an add-on for Cookie Clicker that helps manipulating time so that the right coalescing lump type can be chosen.",
	"ModVersion": 1.3.2,
	"GameVersion": 2.042,
	"Date": "9/09/2021",
	"LanguagePacks": ["lang.js"],
	"Dependencies": ["CCSE"],
	"Disabled": 1
}`.但是游戏无法打开.
我目前的做法是在需要预测的时候打开控制台,输入`Game.LoadMod('https://staticvariablejames.github.io/ChooseYourOwnLump/ChooseYourOwnLump.js');
`来使用,但是这样做太麻烦了,所以,可以为steam版本提供插件吗?

(google translate)
Is there a Steam version for the plugin?
I first tried to create a sub-folder named ChooseYourOwnLump in the Workshop folder, and then created main.js and info.txt in this sub-folder by imitating other plug-ins. https://staticvariablejames.github.io/ChooseYourOwnLump/dist/main.js inside all the content in the main, js, again in the info. txt written inside`{
	"Name": "Choose Your Own Lump!",
	"ID": "Choose Your Own Lump!",
	"Author": "staticvariablejames",
	"Description": "This is an add-on for Cookie Clicker that helps manipulating time so that the right coalescing lump type can be chosen.",
	"ModVersion": 1.3.2,
	"GameVersion": 2.042,
	"Date": "9/09/2021",
	"LanguagePacks": ["lang.js"],
	"Dependencies": ["CCSE"],
	"Disabled": 1
}`.But the game won't open.
My current practice is to open the console and type `Game.LoadMod('https://staticvariablejames.github.io/ChooseYourOwnLump/ChooseYourOwnLump.js');
` when I need a prediction. But it would be too much trouble to do that, so could you provide a plugin for the Steam version?

**Comment by staticvariablejames** [comment]
I wrote an experimental port of CYOL to Steam here: <https://staticvariablejames.github.io/CookieClickerSteamMods/ChooseYourOwnLump.zip>
